[package]
name = "ghostllm-core"
version = "0.1.0"
edition = "2021"
description = "AI inference engine for GhostLLM"

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
default = ["ffi"]
ffi = []